# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  terraform: circleci/terraform@3.0.1

parameters:
  workflow-id:
    type: string
    default: "${CIRCLE_WORKFLOW_ID:0:7}"

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  iglu-server-prep:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Clone Repo
          command: |
            ls -la && pwd
            git clone https://github.com/snowplow/quickstart-examples.git
      - run: 
          name: Patching Iglue Vars File
          command: |
            pwd && ls -la quickstart-examples
            bash -x ./scripts/patch_iglu_vars.sh
            echo "Terraform files have been patched with ENV Vars"
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - quickstart-examples

  iglu-server-build:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /home/circleci/project
      - run:    
          name: Testing repo location
          command: |
              cd /home/circleci/project/quickstart-examples/terraform/aws/iglu_server/default
              echo "My current workspace is : $(pwd)" 
              echo "Lets Deploy the Server"
              terraform init
              cat terraform.tfvars
              terraform validate
              # terraform plan


    # executor: terraform/default
    # steps:
    #   - checkout
    #   - restore_cache:
    #       keys: 
    #         - quickstart-build-iglu
    #   - attach_workspace:
    #       at: ~/
    #   - terraform/init:
    #       path: "~/quickstart-build-iglu/"
    #   - terraform/validate:
    #       path: "."
    #   - terraform/apply:
    #       path: "."


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  quickstart-workflow:
    jobs:
      - iglu-server-prep
      - iglu-server-build:
          requires:
            - iglu-server-prep

