# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  terraform: circleci/terraform@3.0.1

parameters:
  workflow-id:
    type: string
    default: "${CIRCLE_WORKFLOW_ID:0:7}"

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  iglu-server-prep:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Clone Quickstart Repo
          command: |
            git clone https://github.com/snowplow/quickstart-examples.git
      - run: 
          name: Patching Iglu Vars File
          command: |
            bash -x ./scripts/patch_iglu_vars.sh
            echo "Terraform files have been patched with ENV Vars"
      - run: 
          name: Patching Terraform Versions File
          command: |
            cp terraform_files/versions.tf quickstart-examples/terraform/aws/iglu_server/default/versions.tf
            cat quickstart-examples/terraform/aws/iglu_server/default/versions.tf
            echo "Terraform version file has been patched to save state to S3"
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - quickstart-examples

  iglu-server-build:
    docker:
      - image: hashicorp/terraform:1.0.0
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /home/circleci/project
      - run:    
          name: Testing repo location
          command: |
              cd /home/circleci/project/quickstart-examples/terraform/aws/iglu_server/default
              echo "My current workspace is : $(pwd)" 
              echo "Lets Deploy the Server"
              terraform init
              terraform apply -auto-approve

  iglu-server-seed:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /home/circleci/project
      - run:    
          name: Installing IgluCLI
          command: |
              cd /home/circleci/project/quickstart-examples/terraform/aws/iglu_server/default
              wget https://github.com/snowplow-incubator/igluctl/releases/download/0.8.1/igluctl_0.8.1.zip
              unzip igluctl_0.8.1.zip
              chmod +x igluctl
              ./igluctl --version
      - run:    
          name: Seed Iglu Server 
          command: |
              cd /home/circleci/project/quickstart-examples/terraform/aws/iglu_server/default
              ./igluctl --version


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  quickstart-pipeline-deployment:
    jobs:
      - iglu-server-prep
      - iglu-server-build:
          requires:
            - iglu-server-prep
      - iglu-server-seed:
          requires:
            - iglu-server-build
